import numpy as np

from app import __version__
from app.finish import ridge_height
from app.image_processor import tool_path_depths
from app.params import CarveParams
from app.toolpath import Z_STEP, origin_offset, plan_toolpath, quantise  # noqa: F401 (Z_STEP re-exported)

SPINDLE_WARMUP_S = 2


def _fmt(v: float, places: int = 4) -> str:
    return f"{v if v else 0.0:.{places}f}"   # avoid "-0.0000"


def _hm(minutes: float) -> str:
    if minutes < 60:
        return f"{minutes:.1f} min"
    return f"{int(minutes // 60)}h {int(minutes % 60):02d}m"


def generate_gcode(heightmap: np.ndarray, p: CarveParams) -> str:
    rows, cols = heightmap.shape
    x_step = p.width_mm  / max(cols - 1, 1)
    y_step = p.height_mm / max(rows - 1, 1)

    # Tool-centre path: target eroded by the tool profile so the bit never cuts below the image
    q    = quantise(tool_path_depths(heightmap * p.cut_depth, p, x_step, y_step))
    plan = plan_toolpath(q, p, x_step, y_step)
    x_off, y_off = origin_offset(p)

    if p.units == "imperial":
        f, unit, unit_cmd = 1.0 / 25.4, "in", "G20"
        dist, dunit = (lambda mm: f"{mm / 25.4 / 12:.1f}"), "ft"
    else:
        f, unit, unit_cmd = 1.0, "mm", "G21"
        dist, dunit = (lambda mm: f"{mm / 1000:.1f}"), "m"

    dpp = p.depth_per_pass if p.depth_per_pass < p.cut_depth else p.cut_depth
    dia  = f"{_fmt(p.bit_diameter * f)} {unit} diameter"
    tool = {"vbit":     f"V-bit {p.tip_angle:g}° included angle, {dia}",
            "endmill":  f"End mill (flat) {dia}",
            "ballnose": f"Ball nose {dia}"}[p.bit_type]
    minutes = plan.minutes(p) + SPINDLE_WARMUP_S / 60

    slope = 0.0
    if p.bit_type == "endmill":
        gy, gx = np.gradient(heightmap * p.cut_depth, y_step, x_step)
        slope = float(np.hypot(gx, gy).max())
    ridge = ridge_height(p, y_step, slope)
    step_mode = (f"auto, max ridge {_fmt(p.max_ridge * f)} {unit}" if p.step_over_mode == "auto"
                 else f"{p.step_over_pct:g}% of tool diameter")

    lines = [
        "; ============================================================",
        f"; Generated by Molino v{__version__}",
        f"; Physical size:  {_fmt(p.width_mm * f)} x {_fmt(p.height_mm * f)} {unit}",
        f"; Max cut depth:  {_fmt(p.cut_depth * f)} {unit}",
        f"; Depth per pass: {_fmt(dpp * f)} {unit} ({plan.passes} pass{'es' if plan.passes > 1 else ''})",
        f"; Z step:         {_fmt(Z_STEP * f)} {unit}",
        f"; Step over:      {_fmt(x_step * f, 5)} {unit} (X), {_fmt(y_step * f, 5)} {unit} (Y) — {step_mode}",
        f"; Ridge height:   {_fmt(ridge * f)} {unit} between passes for this tool",
        f"; Spindle:        {p.spindle_speed} RPM",
        f"; Feed rate:      {_fmt(p.feed_rate * f)} {unit}/min",
        f"; Plunge rate:    {_fmt(p.plunge_rate * f)} {unit}/min",
        f"; Rapid rate:     {_fmt(p.rapid_rate * f)} {unit}/min (also used for link moves through finished grooves)",
        f"; Retract height: {_fmt(p.retract_height * f)} {unit} (inside carve), "
        f"safe height {_fmt(p.safe_height * f)} {unit} (start/end)",
        f"; Tool:           {tool}",
        "; Tool offset:    path is the image eroded by the tool profile (never cuts below target)",
        f"; Work origin:    X0 Y0 at stock {p.origin}, Z0 at stock top",
        f"; Est. run time:  {_hm(minutes)}  "
        f"(cut {dist(plan.cut_mm)} {dunit}, link {dist(plan.link_mm)} {dunit}, "
        f"rapid {dist(plan.rapid_mm)} {dunit}, plunge {dist(plan.plunge_mm)} {dunit})",
        "; ============================================================",
        "",
        f"{unit_cmd}        ; {unit} units",
        "G90        ; absolute positioning",
        "G17        ; XY plane",
        f"G0 Z{_fmt(p.safe_height * f)}   ; move to safe height",
        "G0 X0 Y0   ; move to origin",
        "T1 M6      ; select tool 1 (remove if no ATC)",
        f"M3 S{p.spindle_speed}   ; start spindle",
        f"G4 P{SPINDLE_WARMUP_S}      ; spindle warm-up",
        "",
    ]

    plunge_f = f" F{_fmt(p.plunge_rate * f)}"
    feed_f   = f" F{_fmt(p.feed_rate * f)}"
    link_f   = f" F{_fmt(p.rapid_rate * f)}"
    retract  = _fmt(p.retract_height * f)

    cur_y, cur_z, cur_f = None, p.safe_height, None

    for op in plan.ops:
        kind = op[0]
        if kind == "pass":
            _, k, n, prev_max, pass_max = op
            if n > 1:
                lines.append(f"; --- Pass {k}/{n}  depth {_fmt(prev_max * f)} → {_fmt(pass_max * f)} {unit} ---")

        elif kind == "hop":
            _, x, y, z = op
            if cur_z < p.retract_height:
                lines.append(f"G0 Z{retract}")
            lines.append(f"G0 X{_fmt((x + x_off) * f)} Y{_fmt((y + y_off) * f)}")
            lines.append(f"G1 Z{_fmt(z * f)}{plunge_f}")
            cur_y, cur_z, cur_f = y, z, plunge_f

        else:
            _, pts, link = op
            # A point is emitted when its (y, z, link) differs from the previous point (ramp /
            # feed-change target) or from the next one (end of a flat run); the rest is redundant.
            key  = np.column_stack((pts[:, 1:], link))
            prev = np.vstack(([cur_y, cur_z, False], key[:-1]))
            start_diff = np.any(key != prev, axis=1)
            end_diff   = np.append(np.any(key[1:] != key[:-1], axis=1), True)
            for i in np.flatnonzero(start_diff | end_diff):
                x, y, z = pts[i]
                s = f"G1 X{_fmt((x + x_off) * f)}"
                if y != cur_y:
                    s += f" Y{_fmt((y + y_off) * f)}"
                    cur_y = y
                if z != cur_z:
                    s += f" Z{_fmt(z * f)}"
                    cur_z = z
                want_f = link_f if link[i] else feed_f
                if want_f != cur_f:
                    s += want_f
                    cur_f = want_f
                lines.append(s)

    lines += [
        "",
        f"G0 Z{_fmt(p.safe_height * f)}   ; lift to safe height",
        "G0 X0 Y0   ; return to origin",
        "M5         ; stop spindle",
        "M2         ; end program",
    ]
    return "\n".join(lines)
