import math

import numpy as np

from app import __version__
from app.params import CarveParams

# Minimum Z increment — matches typical CNC step resolution.
# Depths are quantised to this grid so programmed Z = executed Z.
Z_STEP = 0.01  # mm


def _fmt(v: float, places: int = 4) -> str:
    return f"{v if v else 0.0:.{places}f}"   # avoid "-0.0000"


def generate_gcode(heightmap: np.ndarray, p: CarveParams) -> str:
    rows, cols = heightmap.shape

    depth_per_pass = p.depth_per_pass if p.depth_per_pass < p.cut_depth else p.cut_depth
    num_passes = math.ceil(p.cut_depth / depth_per_pass)

    if p.units == "imperial":
        f, unit, unit_cmd = 1.0 / 25.4, "in", "G20"
    else:
        f, unit, unit_cmd = 1.0, "mm", "G21"

    x_step = p.width_mm  / max(cols - 1, 1)
    y_step = p.height_mm / max(rows - 1, 1)

    q_depths = np.round(heightmap * p.cut_depth / Z_STEP) * Z_STEP   # mm, quantised
    row_max  = q_depths.max(axis=1)

    tool = (f"V-bit {p.tip_angle:g}° included angle, {_fmt(p.bit_diameter * f)} {unit} diameter"
            if p.bit_type == "vbit" else
            f"End mill {_fmt(p.bit_diameter * f)} {unit} diameter")

    lines = [
        "; ============================================================",
        f"; Generated by Molino v{__version__}",
        f"; Physical size:  {_fmt(p.width_mm * f)} x {_fmt(p.height_mm * f)} {unit}",
        f"; Max cut depth:  {_fmt(p.cut_depth * f)} {unit}",
        f"; Depth per pass: {_fmt(depth_per_pass * f)} {unit} "
        f"({num_passes} pass{'es' if num_passes > 1 else ''})",
        f"; Z step:         {_fmt(Z_STEP * f)} {unit}",
        f"; Step over:      {_fmt(x_step * f, 5)} {unit} (X), {_fmt(y_step * f, 5)} {unit} (Y)",
        f"; Spindle:        {p.spindle_speed} RPM",
        f"; Feed rate:      {_fmt(p.feed_rate * f)} {unit}/min",
        f"; Plunge rate:    {_fmt(p.plunge_rate * f)} {unit}/min",
        f"; Tool:           {tool}",
        "; ============================================================",
        "",
        f"{unit_cmd}        ; {unit} units",
        "G90        ; absolute positioning",
        "G17        ; XY plane",
        f"G0 Z{_fmt(p.safe_height * f)}   ; move to safe height",
        "G0 X0 Y0   ; move to origin",
        "T1 M6      ; select tool 1 (remove if no ATC)",
        f"M3 S{p.spindle_speed}   ; start spindle",
        "G4 P2      ; spindle warm-up 2 s",
        "",
    ]

    safe   = f"G0 Z{_fmt(p.safe_height * f)}"
    plunge = f" F{_fmt(p.plunge_rate * f)}"
    feed   = f" F{_fmt(p.feed_rate * f)}"

    for pass_num in range(1, num_passes + 1):
        pass_max = min(pass_num * depth_per_pass, p.cut_depth)
        prev_max = (pass_num - 1) * depth_per_pass

        if num_passes > 1:
            lines.append(f"; --- Pass {pass_num}/{num_passes}  depth "
                         f"{_fmt(prev_max * f)} → {_fmt(pass_max * f)} {unit} ---")

        for r in range(rows):
            # Row already at final depth from earlier passes — nothing left to remove
            if row_max[r] <= prev_max + 1e-9:
                continue

            forward = r % 2 == 0
            order   = range(cols) if forward else range(cols - 1, -1, -1)
            depths  = np.minimum(q_depths[r], pass_max)
            y       = r * y_step

            first = order[0]
            z = -float(depths[first])
            lines.append(safe)
            lines.append(f"G0 X{_fmt(first * x_step * f)} Y{_fmt(y * f)}")
            lines.append(f"G1 Z{_fmt(z * f)}{plunge}")

            prev_z = z
            for i, c in enumerate(order[1:]):
                z  = -float(depths[c])
                xs = f"G1 X{_fmt(c * x_step * f)}"
                if abs(z - prev_z) >= Z_STEP - 1e-9:
                    xs += f" Z{_fmt(z * f)}"
                    prev_z = z
                lines.append(xs + (feed if i == 0 else ""))

    lines += [
        "",
        f"{safe}   ; lift to safe height",
        "G0 X0 Y0   ; return to origin",
        "M5         ; stop spindle",
        "M2         ; end program",
    ]
    return "\n".join(lines)
