import numpy as np


def generate_gcode(heightmap: np.ndarray, params: dict) -> str:
    rows, cols = heightmap.shape

    width_mm = float(params.get("width_mm", 100.0))
    height_mm = float(params.get("height_mm", 100.0))
    cut_depth_mm = float(params.get("cut_depth", 3.0))
    safe_height = float(params.get("safe_height", 5.0))
    spindle_speed = int(params.get("spindle_speed", 12000))
    feed_rate = float(params.get("feed_rate", 1000.0))
    plunge_rate = float(params.get("plunge_rate", 300.0))
    bit_type = params.get("bit_type", "vbit")
    bit_diameter = float(params.get("bit_diameter", 3.175))
    tip_angle = float(params.get("tip_angle", 60.0))

    imperial = params.get("units", "metric") == "imperial"
    if imperial:
        # All values arrive in mm; convert to inches for G-code output
        f = 1.0 / 25.4
        unit_label = "in"
        unit_cmd = "G20"
    else:
        f = 1.0
        unit_label = "mm"
        unit_cmd = "G21"

    x_step = width_mm / max(cols - 1, 1)
    y_step = height_mm / max(rows - 1, 1)

    lines = [
        "; ============================================================",
        "; Generated by Molino v0.03",
        f"; Physical size: {width_mm * f:.4f} x {height_mm * f:.4f} {unit_label}",
        f"; Max cut depth: {cut_depth_mm * f:.4f} {unit_label}",
        f"; Step over: {x_step * f:.5f} {unit_label} (X), {y_step * f:.5f} {unit_label} (Y)",
        f"; Spindle: {spindle_speed} RPM",
        f"; Feed rate: {feed_rate * f:.4f} {unit_label}/min",
        f"; Plunge rate: {plunge_rate * f:.4f} {unit_label}/min",
    ]

    if bit_type == "vbit":
        lines.append(f"; Tool: V-bit {tip_angle}° included angle, {bit_diameter * f:.4f} {unit_label} diameter")
    else:
        lines.append(f"; Tool: End mill {bit_diameter * f:.4f} {unit_label} diameter")

    lines += [
        "; ============================================================",
        "",
        f"{unit_cmd}        ; {unit_label} units",
        "G90        ; absolute positioning",
        "G17        ; XY plane",
        f"G0 Z{safe_height * f:.4f}   ; move to safe height",
        "G0 X0 Y0   ; move to origin",
        f"M3 S{spindle_speed}   ; start spindle",
        "G4 P2      ; spindle warm-up 2 s",
        "",
    ]

    for row_idx in range(rows):
        y = row_idx * y_step
        forward = row_idx % 2 == 0
        col_range = range(cols) if forward else range(cols - 1, -1, -1)
        first_col = 0 if forward else cols - 1

        start_x = first_col * x_step
        start_z = -heightmap[row_idx, first_col] * cut_depth_mm

        lines.append(f"G0 Z{safe_height * f:.4f}")
        lines.append(f"G0 X{start_x * f:.4f} Y{y * f:.4f}")
        lines.append(f"G1 Z{start_z * f:.5f} F{plunge_rate * f:.4f}")
        lines.append(f"F{feed_rate * f:.4f}")

        prev_z = start_z
        for col_idx in col_range:
            x = col_idx * x_step
            z = -heightmap[row_idx, col_idx] * cut_depth_mm
            if abs(z - prev_z) > 0.0005:
                lines.append(f"G1 X{x * f:.4f} Z{z * f:.5f}")
                prev_z = z
            else:
                lines.append(f"G1 X{x * f:.4f}")

    lines += [
        "",
        f"G0 Z{safe_height * f:.4f}   ; lift to safe height",
        "G0 X0 Y0   ; return to origin",
        "M5         ; stop spindle",
        "M2         ; end program",
    ]

    return "\n".join(lines)
